INSERT INTO municipio (cod_dep, nombre) VALUES
(1,'Leticia'),
(1,'C.D. El Encanto'),
(1,'C.D. La Chorrera'),
(1,'C.D. La Pedrera'),
(1,'C.D. Mirití-Paraná'),
(1,'Puerto Nariño'),
(1,'C.D. Puerto Santander'),
(1,'C.D. Tarapacá'),
(2,'Medellín'),
(2,'Abejorral'),
(2,'Abriaquí'),
(2,'Alejandría'),
(2,'Amagá'),
(2,'Amalfi'),
(2,'Andes'),
(2,'Angelopolis '),
(2,'Angostura'),
(2,'Anori'),
(2,'Antioquia'),
(2,'Anza'),
(2,'Apartado'),
(2,'Arboletes'),
(2,'Argelia'),
(2,'Armenia'),
(2,'Barbosa'),
(2,'Belmira'),
(2,'Bello'),
(2,'Betania'),
(2,'Betulia'),
(2,'Bolivar'),
(2,'Briceno '),
(2,'Buritica'),
(2,'Caceres'),
(2,'Caicedo'),
(2,7),
(2,'Campamento'),
(2,'Cañasgordas'),
(2,'Caracoli'),
(2,'Caramanta'),
(2,'Carepa'),
(2,'Carmen de Viboral'),
(2,'Carolina'),
(2,'Caucasia'),
(2,'Chigorodo'),
(2,'Cisneros'),
(2,'Cocorna'),
(2,'Concepción'),
(2,'Concordia'),
(2,'Copacabana'),
(2,'Dabeiba'),
(2,'Don Matias'),
(2,'Ebejico'),
(2,'El Bagre'),
(2,'Entrerrios'),
(2,'Envigado'),
(2,'Fredonia'),
(2,'Frontino'),
(2,'Giraldo'),
(2,'Girardota'),
(2,'Gomez Plata'),
(2,'Granada'),
(2,'Guadalupe'),
(2,'Guarne'),
(2,'Guatape'),
(2,'Heliconia'),
(2,'Hispania'),
(2,'Itagui'),
(2,'Ituango'),
(2,'Jardín'),
(2,'Jerico'),
(2,'La Ceja'),
(2,'La Estrella'),
(2,'La Unión'),
(2,'Liborina'),
(2,'Maceo'),
(2,'Marinilla'),
(2,'Montebello'),
(2,'Murindo'),
(2,'Mutata'),
(2,'Nari'),
(2,'Necocli'),
(2,'Nechi'),
(2,'Olaya'),
(2,'Penol'),
(2,'Peque'),
(2,'Pueblorrico'),
(2,'Puerto Berrio'),
(2,'Puerto Nare '),
(2,'Puerto Triunfo '),
(2,'Remedios'),
(2,'Retiro'),
(2,'Rionegro'),
(2,'Sabanalarga'),
(2,'Sabaneta'),
(2,'Salgar'),
(2,'San Andrés'),
(2,'San Carlos'),
(2,'San Francisco'),
(2,'San Jerónimo'),
(2,'S. José La Monta'),
(2,'S. Juan de Uraba'),
(2,'San Luis'),
(2,'San Pedro'),
(2,'San Pedro de Uraba'),
(2,'San Rafael'),
(2,'San Roque'),
(2,'San Vicente'),
(2,'Santa Bárbara'),
(2,'Santa Rosa D. Osos'),
(2,'Santo Domingo'),
(2,'Santuario'),
(2,'Segovia'),
(2,'Sonson'),
(2,'Sopetran'),
(2,'Tamesis'),
(2,'Taraza'),
(2,'Tarso'),
(2,'Titiribi'),
(2,'Toledo'),
(2,'Turbo'),
(2,'Uramita'),
(2,'Urrao'),
(2,'Valdivia'),
(2,'Valparaiso'),
(2,'Vegachi'),
(2,'Venecia'),
(2,'Vigia del Fuerte'),
(2,'Yali'),
(2,'Yarumal'),
(2,'Yolombo'),
(2,'Yondo'),
(2,'Zaragoza'),
(3,'Arauca'),
(3,'Arauquita'),
(3,'Cravo Norte'),
(3,'Fortul'),
(3,'Puerto Rondon '),
(3,'Saravena'),
(3,'Tame '),
(4,'Barranquilla'),
(4,'Baranoa'),
(4,'Campo de la Cruz'),
(4,'Candelaria'),
(4,'Galapa'),
(4,'Juan de Acosta'),
(4,'Luruaco'),
(4,'Malambo'),
(4,'Manati'),
(4,'Palmar D. Varela'),
(4,'Piojo'),
(4,'Polonuevo'),
(4,'Ponedera'),
(4,'Puerto Colombia'),
(4,'Repelon'),
(4,'Sabanagrande'),
(4,'Sabanalarga'),
(4,'Santa Lucía'),
(4,'Santo Tomás'),
(4,'Soledad'),
(4,'Suan'),
(4,'Tubara'),
(4,'Usiacuri '),
(5,'Cartagena'),
(5,'Achi'),
(5,'Arjona'),
(5,'Barranco de Loba'),
(5,'Calamar'),
(5,'Cordoba'),
(5,'El Carmen de Bolívar'),
(5,'El Guamo'),
(5,'Magangue'),
(5,'Mahates'),
(5,'Margarita'),
(5,'María La Baja'),
(5,'Mompos'),
(5,'Morales'),
(5,'Pinillos'),
(5,'Río Viejo'),
(5,'San Estanislao'),
(5,'San Fernando'),
(5,'San Jacinto'),
(5,'San Juan Nepomuceno'),
(5,'San Martín de Loba'),
(5,'San Pablo'),
(5,'Santa Catalina'),
(5,'Santa Rosa'),
(5,'Santa Rosa del Sur'),
(5,'Simiti'),
(5,'Soplaviento'),
(5,'Talaigua Nuevo'),
(5,'Turbaco'),
(5,'Turbana'),
(5,'Villanueva'),
(5,'Zambrano'),
(6,'Tunja '),
(6,'Almeida'),
(6,'Aquitania'),
(6,'Arcabuco'),
(6,'Belén'),
(6,'Berbeo'),
(6,'Beteitiva'),
(6,'Boavita'),
(6,'Boyaca'),
(6,'Briceno'),
(6,'Buenavista'),
(6,'Busbanza'),
(6,7),
(6,'Campohermoso'),
(6,'Cerinza'),
(6,'Chinavita'),
(6,'Chiquinquira '),
(6,'Chiscas'),
(6,'Chita'),
(6,'Chitaraque'),
(6,'Chivata'),
(6,'Cienega'),
(6,'Combita'),
(6,'Coper'),
(6,'Corrales'),
(6,'Covarachia'),
(6,'Cubara'),
(6,'Cucaita'),
(6,'Cuitiva'),
(6,'Chiquiza'),
(6,'Chivor'),
(6,'Duitama '),
(6,'El Cocuy'),
(6,'El Espino'),
(6,'Firavitoba'),
(6,'Floresta'),
(6,'Gachantiva'),
(6,'Gameza'),
(6,'Garagoa'),
(6,'Guacamayas'),
(6,'Guateque'),
(6,'Guayata'),
(6,'Guican'),
(6,'Iza'),
(6,'Jenesano'),
(6,'Jerico'),
(6,'Labranzagrande'),
(6,'La Capilla'),
(6,'La Victoria'),
(6,'La Uvita'),
(6,'Leiva'),
(6,'Macanal'),
(6,'Maripi'),
(6,'Miraflores'),
(6,'Mongua'),
(6,'Mongui'),
(6,'Moniquira'),
(6,'Motavita'),
(6,'Muzo'),
(6,'Nobsa'),
(6,'Nuevo Colón'),
(6,'Oicata'),
(6,'Otanche'),
(6,'Pachayita'),
(6,'Paez'),
(6,'Paipa'),
(6,'Pajarito'),
(6,'Panqueba'),
(6,'Pauna'),
(6,'Paya'),
(6,'Paz de Río'),
(6,'Pesca'),
(6,'Pisva'),
(6,'Puerto Boyaca'),
(6,'Quipama'),
(6,'Ramiriqui'),
(6,'Raquira'),
(6,'Rondon'),
(6,'Saboya'),
(6,'Sachica'),
(6,'Samaca'),
(6,'San Eduardo'),
(6,'S. José de Pare'),
(6,'S. Luis D. Gaceno'),
(6,'San Mateo'),
(6,'San Miguel D. Sema'),
(6,'San Pablo Borbur'),
(6,'Santana'),
(6,'Santa María'),
(6,'S. Rosa Viterbo'),
(6,'Santa Sofía'),
(6,'Sativanorte'),
(6,'Sativasur'),
(6,'Siachoque'),
(6,'Soata'),
(6,'Socota'),
(6,'Socha'),
(6,'Sogamoso'),
(6,'Somondoco'),
(6,'Sora'),
(6,'Sotaquira'),
(6,'Soraca'),
(6,'Susacon'),
(6,'Sutamarchan'),
(6,'Sutatenza'),
(6,'Tasco'),
(6,'Tenza'),
(6,'Tibana'),
(6,'Tibasosa'),
(6,'Tinjaca'),
(6,'Tipacoque'),
(6,'Toca'),
(6,'Togui'),
(6,'Topaga'),
(6,'Tota'),
(6,'Tunungua'),
(6,'Turmeque'),
(6,'Tuta'),
(6,'Tutasa'),
(6,'Umbita'),
(6,'Ventaquemada'),
(6,'Viracacha'),
(6,'Zetaquira'),
(7,'Manizales '),
(7,'Aguadas'),
(7,'Anserma'),
(7,'Aranzazu'),
(7,'Belalcazar'),
(7,'Chinchina'),
(7,'Filadelfia'),
(7,'La Dorada'),
(7,'La Merced'),
(7,'Manzanares'),
(7,'Marmato'),
(7,'Marquetalia'),
(7,'Marulanda'),
(7,'Neira'),
(7,'Pacora'),
(7,'Palestina '),
(7,'Pensilvania'),
(7,'Riosucio'),
(7,25),
(7,'Salamina'),
(7,'Samana'),
(7,'Supia'),
(7,'Victoria'),
(7,'Villamaría'),
(7,'Viterbo '),
(8,'Florencia'),
(8,'Albania'),
(8,'Belen Andaquies'),
(8,'Cartagena de Chaira'),
(8,'Currillo'),
(8,'El Doncello'),
(8,'El Paujil'),
(8,'La Montanita'),
(8,'MIlán'),
(8,'Morelia'),
(8,'Puerto Rico'),
(8,'S. José de la Fragua'),
(8,'S. Vicente Caguán'),
(8,'Solano '),
(8,'Valparaíso'),
(9,'Yopal '),
(9,'Aguazul'),
(9,'Chameza'),
(9,'Hato Corozal'),
(9,'La Salina'),
(9,'Mani'),
(9,'Monterrey'),
(9,'Nunchia'),
(9,'Orocue'),
(9,'Paz de Ariporo'),
(9,'Pore'),
(9,'Recetor'),
(9,'Sabanalarga'),
(9,'Sacama'),
(9,'S. Luis d. Palenque'),
(9,'Tamara'),
(9,'Tauramena '),
(9,'Trinidad'),
(9,'Villanueva '),
(10,'Popayán '),
(10,'Almaguer'),
(10,'Argelia'),
(10,'Balboa'),
(10,5),
(10,'Buenos Aires'),
(10,'Cajibío'),
(10,'Caldono'),
(10,'Caloto'),
(10,'Corinto'),
(10,'El Tambo'),
(10,'Florencia'),
(10,'Guapi'),
(10,'Inzá'),
(10,'Jambaló'),
(10,'La Sierra'),
(10,'La Vega '),
(10,'López'),
(10,'Mercaderes'),
(10,'Miranda'),
(10,'Morales'),
(10,'Padilla'),
(10,'Páez'),
(10,'Patía (El Bordo)'),
(10,'Piendamó'),
(10,'Puerto Tejada'),
(10,'Puracé'),
(10,'Rosas'),
(10,'San Sebastián'),
(10,26),
(10,'Santa Rosa'),
(10,'Silvia'),
(10,'Sotará'),
(10,'Suárez'),
(10,'Timbío'),
(10,'Timbiquí'),
(10,'Toribío'),
(10,'Totoro '),
(11,'Valledupar'),
(11,'Aguachica'),
(11,'Agustin Codazzi'),
(11,'Astrea'),
(11,'Becerril'),
(11,'Bosconia'),
(11,'Chimichagua'),
(11,'Chiriguana'),
(11,'Curumani'),
(11,'El Copey'),
(11,'El Paso'),
(11,'Gamarra'),
(11,'González'),
(11,'La Gloria'),
(11,'La Jagua Ibirico'),
(11,'Manaure Balcón César'),
(11,'Pailitas'),
(11,'Pelaya'),
(11,'Río de Oro'),
(11,'Robles La Paz'),
(11,'San Alberto'),
(11,'San Diego'),
(11,'San Martín'),
(11,'Tamalameque'),
(12,'Montería'),
(12,'Ayapel'),
(12,'Buenavista '),
(12,'Canalete'),
(12,'Cerete'),
(12,'Chima'),
(12,'Chinu'),
(12,'Cienaga de Oro'),
(12,'Lorica'),
(12,'Los Córdobas'),
(12,'Momil'),
(12,'Montelibano '),
(12,'Monitos'),
(12,'Planeta Rica'),
(12,'Pueblo Nuevo'),
(12,'PUerto Escondido'),
(12,'Puerto Libertador '),
(12,'Purísima'),
(12,'Sahagún'),
(12,'S. Andrés Sotavento'),
(12,'San Antero'),
(12,'San Bernardo Vto.'),
(12,'San Carlos'),
(12,'San Pelayo'),
(12,'Tierralta'),
(12,'Valencia'),
(13,'Bogotá'),
(13,'Agua de Dios'),
(13,'Alban'),
(13,'Anapoima'),
(13,'Anolaima'),
(13,'Arbelaez'),
(13,'Beltrán'),
(13,'Bituima'),
(13,'Bojaca'),
(13,'Cabrera'),
(13,'Cachipay'),
(13,'Cajica'),
(13,'Caparrapi'),
(13,'Caqueza'),
(13,'Carmen D. Carupa'),
(13,'Chaguani'),
(13,'Chia'),
(13,'Chipaque'),
(13,'Choachi'),
(13,'Choconta'),
(13,'Cogua'),
(13,'Cota'),
(13,'Cucunuba'),
(13,'El Colegio'),
(13,'El Penon'),
(13,'Facatativa'),
(13,'Fomeque'),
(13,'Fosca'),
(13,'Funza'),
(13,'Fuquene'),
(13,'Fusagasuga'),
(13,'Gachala'),
(13,'Gachancipa'),
(13,'Gacheta'),
(13,'Gama'),
(13,'Girardot'),
(13,'Guacheta'),
(13,'Guaduas'),
(13,'Guasca'),
(13,'Guataqui'),
(13,'Guatavita'),
(13,'Guayabal Siquim'),
(13,'Guayabetal'),
(13,'Gutierrez'),
(13,'Jerusalen'),
(13,'Junin'),
(13,'La Calera'),
(13,'La Mesa'),
(13,'La Palma'),
(13,'La Pena'),
(13,'La Vega'),
(13,'Lenguazaque'),
(13,'Macheta'),
(13,'Madrid'),
(13,'Manta'),
(13,'Medina'),
(13,'Mosquera'),
(13,'Narino'),
(13,'Nemocon'),
(13,'Nilo'),
(13,'NImaima'),
(13,'Nocaima'),
(13,'Ospina Pérez'),
(13,'Pacho'),
(13,'Paime'),
(13,'Pandi '),
(13,'Paratebueno'),
(13,'Pasca'),
(13,'Puerto Salgar'),
(13,'Puli'),
(13,'Quebradanegra'),
(13,'Quetame'),
(13,'Quipile'),
(13,'Rafael Reyes'),
(13,'Ricaurte'),
(13,'S. Ant. de Tena'),
(13,'San Bernardo'),
(13,'San Cayetano'),
(13,'San Francisco'),
(13,'San Juan Rioseco'),
(13,'Sasaima'),
(13,'Sesquile'),
(13,'Sibate'),
(13,'Silvania'),
(13,'Simijaca'),
(13,'Soacha'),
(13,'Sopo'),
(13,'Subachoque'),
(13,'Suesca'),
(13,'Supata'),
(13,'Susa'),
(13,'Sutatausa'),
(13,'Tabio'),
(13,'Tausa'),
(13,'Tena'),
(13,'Tenio'),
(13,'Tibacuy'),
(13,'Tibirita'),
(13,'Tocaima'),
(13,'Tocancipa'),
(13,'Topaipi'),
(13,'Ubala'),
(13,'Ubaque'),
(13,'Ubate'),
(13,'Une'),
(13,'Utica'),
(13,'Vergara'),
(13,'Viani'),
(13,'Villagomez'),
(13,'Villapinzón'),
(13,'Villeta'),
(13,'Viota'),
(13,'Yacopi'),
(13,'Zipacon'),
(13,'Zipaquira'),
(14,'Quibdó'),
(14,'Acandi'),
(14,'Alto Baudo'),
(14,'Bagado'),
(14,'Bahía Solano'),
(14,'Bajo Baudo'),
(14,'Litoral de San Juan'),
(14,'Bojaya (Bellavista)'),
(14,'Condoto'),
(14,'El Carmen'),
(14,'Istmina'),
(14,'Jurado'),
(14,'Lloro'),
(14,'Novita'),
(14,'Nuqui'),
(14,'Riosucio'),
(14,'San José del Palmar '),
(14,'Sipi'),
(14,'Tado'),
(14,'Unguia '),
(15,'Inírida'),
(15,'C.D. Guaviare'),
(15,'C.D. San Felipe'),
(15,'C.D. Puerto Colombia'),
(15,'C.D. La Guadalupe'),
(15,'C.D. Cacahual'),
(15,'C.D. Pana Pana'),
(15,'C.D. Morichal Nuevo'),
(16,'San José del Guaviare'),
(16,'Calamar'),
(16,'El Retorno'),
(16,'Miraflores '),
(17,'Neiva'),
(17,'Acevedo'),
(17,'Agrado'),
(17,'Aipe'),
(17,'Algeciras'),
(17,'Altamira'),
(17,'Baraya'),
(17,'Campoalegre'),
(17,'Colombia'),
(17,'Elias'),
(17,'Garzón'),
(17,'Gigante'),
(17,'Guadalupe'),
(17,'Hobo'),
(17,'Iquira'),
(17,'Isnos'),
(17,'La Argentina'),
(17,'La Plata'),
(17,'Nataga'),
(17,'Oporapa'),
(17,'Paicol'),
(17,'Palermo'),
(17,'Palestina'),
(17,'Pital'),
(17,'Pitalito'),
(17,'Rivera'),
(17,'Saladoblanco'),
(17,'San Agustín'),
(17,'Santa María'),
(17,'Suaza'),
(17,'Tarqui'),
(17,'Tesalia'),
(17,'Tello'),
(17,'Teruel'),
(17,'Timana'),
(17,'Villavieja'),
(17,'Yaguara'),
(18,'Riohacha'),
(18,'Barrancas'),
(18,'El Molino'),
(18,'Fonseca'),
(18,'Maicao'),
(18,'Manaure'),
(18,'S. Juan D. Cesar'),
(18,'Uribia'),
(18,'Urumita'),
(18,'Villanueva'),
(19,'Santa Marta'),
(19,'Aracataca'),
(19,'Ariguani'),
(19,'Cerro S. Antonio'),
(19,'Chivolo'),
(19,'Cienaga'),
(19,'El Banco'),
(19,'El Pinon'),
(19,'Fundación'),
(19,'Guamal'),
(19,'Pedraza'),
(19,'Pivijay '),
(19,'Plato'),
(19,'Puebloviejo'),
(19,'Remolino'),
(19,'Salamina'),
(19,'S. Sebastián B.'),
(19,'San Zenón'),
(19,'Santa Ana'),
(19,'Sitionuevo'),
(19,'Tenerife '),
(20,'Villavicencio'),
(20,'Acacias'),
(20,'Barrande de Upia'),
(20,'Cabuyaro'),
(20,'Castilla La Nva.'),
(20,'Cubarral '),
(20,'Cumaral'),
(20,'El Calvario'),
(20,'El Castillo'),
(20,'El Dorado'),
(20,'Fuente de Oro'),
(20,'Granada'),
(20,'Guamal'),
(20,'Mapiripan'),
(20,'Mesetas'),
(20,'La Macarena'),
(20,'La Uribe'),
(20,'Lejanias'),
(20,'Puerto Concordia'),
(20,'Puerto Gaitan'),
(20,'Puerto López'),
(20,'Puerto Lleras '),
(20,'Puerto Rico'),
(20,'Restrepo'),
(20,'S. Carlos Guaroa'),
(20,'S. Juan de Arama'),
(20,'San Juanito'),
(20,'San Martín'),
(20,'Vista Hermosa '),
(21,'Pasto '),
(21,'Alban'),
(21,'Aldana'),
(21,'Ancuya'),
(21,'Arboleda'),
(21,'Barbacoas'),
(21,'Belen'),
(21,'Buesaco'),
(21,'Colon (Genova)'),
(21,'Consaca'),
(21,'Contadero'),
(21,'Cordoba'),
(21,'Cuaspud'),
(21,'Cumbal'),
(21,'Cumbitara'),
(21,'Chachagui '),
(21,'El Charco'),
(21,'El Rosario'),
(21,'El Tablon'),
(21,'El Tambo'),
(21,'Funes'),
(21,'Guachucal'),
(21,'Guaitarilla'),
(21,'Gualmatan'),
(21,'Iles'),
(21,'Imues'),
(21,'Ipiales'),
(21,'La Cruz'),
(21,'La Florida'),
(21,'La Llanada'),
(21,'La Tola'),
(21,'La Unión '),
(21,'Leiva'),
(21,'Linares'),
(21,'Los Andes'),
(21,'Magui'),
(21,'Mallama'),
(21,'Mosquera'),
(21,'Olaya Herrera'),
(21,'Ospina'),
(21,'Francisco Pizarro'),
(21,'Policarpa'),
(21,'Potosí'),
(21,'Providencia'),
(21,'Puerres'),
(21,'Pupiales'),
(21,'Ricaurte'),
(21,'Roberto Payan'),
(21,'Samaniego'),
(21,'Sandona'),
(21,'San Bernardo'),
(21,'San Lorenzo'),
(21,'San Pablo'),
(21,'San Pedro de Cartago'),
(21,'Santa Bárbara'),
(21,'Santacruz'),
(21,'Sapuyes'),
(21,'Taminango'),
(21,'Tangua'),
(21,'Tumaco'),
(21,'Tuquerres'),
(21,'Yacuanquer '),
(22,'Cúcuta'),
(22,'Abrego'),
(22,'Arboledas'),
(22,'Bochalema'),
(22,'Bucarasica'),
(22,'Cacota'),
(22,'Cachira'),
(22,'Chinacota'),
(22,'Chitaga'),
(22,'Convención'),
(22,'Cucutilla'),
(22,'Durania'),
(22,'El Carmen'),
(22,'El Tarra'),
(22,'El Zulia'),
(22,'Gramalote'),
(22,'Hacari '),
(22,'Herran'),
(22,'Labateca'),
(22,'La Playa'),
(22,'Los Patios'),
(22,'Lourdes'),
(22,'Mutiscua'),
(22,'Ocana'),
(22,'Pamplona'),
(22,'Pamplonita'),
(22,'Ragonvalia'),
(22,'Salazar'),
(22,'San Calixto'),
(22,'San Cayetano'),
(22,'Santiago'),
(22,'Sardinata'),
(22,'Silos '),
(22,'Teorama'),
(22,'Tibu'),
(22,'Toledo'),
(22,'Villa Caro'),
(22,'Villa Rosario '),
(23,'Mocoa'),
(23,'Colon'),
(23,'Orito'),
(23,'Puerto Asis'),
(23,'Puerto Caicedo'),
(23,'Puerto Guzman'),
(23,'Puerto Leguizam'),
(23,'Sibundoy'),
(23,'San Francisco'),
(23,'Santiago'),
(23,'Valle del Guamez'),
(23,'Villa Garzón'),
(24,'Armenia'),
(24,'Buenavista'),
(24,'Calarca'),
(24,'Circasia'),
(24,'Cordoba'),
(24,'Filandia'),
(24,'Genova'),
(24,'La Tebaida'),
(24,'Montenegro'),
(24,'Pijao'),
(24,'Quimbaya'),
(24,'Salento '),
(25,'Pereira'),
(25,'Apia'),
(25,'Balboa'),
(25,'Belen de Umbria'),
(25,'Dos Quebradas'),
(25,'Guatica'),
(25,'La Celia'),
(25,'La Virginia'),
(25,'Marsella'),
(25,'Mistrato'),
(25,'Pueblo Rico'),
(25,'Quinchia'),
(25,'S. Rosa de Cabal '),
(25,'Santuario '),
(26,'Bucaramanga'),
(26,'Aguada'),
(26,'Albania'),
(26,'Aratoca'),
(26,'Barbosa'),
(26,'Barichara'),
(26,'Barrancabermeja'),
(26,'Betulia'),
(26,'Bolívar '),
(26,'Cabrera'),
(26,'California'),
(26,'Capitanejo'),
(26,'Carcasi'),
(26,'Cepita'),
(26,'Cerrito'),
(26,'Charala'),
(26,'Charta'),
(26,'Chima'),
(26,'Chipata'),
(26,'Cimitarra'),
(26,'Concepción'),
(26,'Confines'),
(26,'Contratación'),
(26,'Coromoro'),
(26,'Curiti '),
(26,'El Carmen'),
(26,'El Guacamayo'),
(26,'El Penon'),
(26,'El Playon'),
(26,'Encino'),
(26,'Enciso'),
(26,'El Florian'),
(26,'Floridablanca'),
(26,'Galan'),
(26,'Gambita'),
(26,'Giron'),
(26,'Guaca'),
(26,'Guadalupe'),
(26,'Guapota'),
(26,'Guavata'),
(26,'Guepsa'),
(26,'Hato'),
(26,'Jesús María'),
(26,'Jordan'),
(26,'La Belleza'),
(26,'Landazuri'),
(26,'La Paz'),
(26,'Lebrija'),
(26,'Los Santos'),
(26,'Macaravita'),
(26,'Malaga'),
(26,'Matanza'),
(26,'Mogotes'),
(26,'Molagavita'),
(26,'Ocamonte'),
(26,'Oiba '),
(26,'Onzaga'),
(26,'Palmar'),
(26,'Palmas Socorro'),
(26,'Paramo'),
(26,'Piedecuesta'),
(26,'Pinchote'),
(26,'Puente Nacional'),
(26,'Puerto Parra'),
(26,'Puerto Wilches'),
(26,'Rionegro'),
(26,'Sabana de Torre'),
(26,'San Benito'),
(26,'San Gil'),
(26,'San Joaquin'),
(26,'San José Miranda'),
(26,'San Miguel '),
(26,'San Vicente de Ch.'),
(26,'Santa Bárbara'),
(26,'Santa Helena del Opon'),
(26,'Simacota'),
(26,'Socorro'),
(26,'Suaita'),
(26,'Sucre'),
(26,'Surata'),
(26,'Tona'),
(26,'Valle San José'),
(26,'Velez'),
(26,'Vetas'),
(26,'Villanueva'),
(26,'Zapatoca '),
(27,'San Andrés'),
(27,'Providencia y Santa Catalina '),
(28,'Sincelejo '),
(28,'Buenavista'),
(28,'Caimito'),
(28,'Coloso'),
(28,'Corozal'),
(28,'Chalan'),
(28,'Galeras'),
(28,'Guaranda'),
(28,'La Unión'),
(28,'Los Palmitos'),
(28,'Majagual'),
(28,'Morroa'),
(28,'Ovejas'),
(28,'Palmito'),
(28,'Sampues'),
(28,'San Benito Abad'),
(28,'San Juan Betulia '),
(28,'San Marcos'),
(28,'San Onofre'),
(28,'San Pedro'),
(28,'Since'),
(28,'Sucre'),
(28,'Tolu'),
(28,'Toluviejo '),
(29,'Ibagué'),
(29,'Alpujarra'),
(29,'Alvarado'),
(29,'Ambalema'),
(29,'Anzoategui'),
(29,'Armero (Guayabal)'),
(29,'Ataco'),
(29,'Cajamarca'),
(29,'Carmen Apicala'),
(29,'Casabianca'),
(29,'Chaparral'),
(29,'Coello'),
(29,'Coyaima'),
(29,'Cunday'),
(29,'Dolores'),
(29,'Espinal'),
(29,'Falan '),
(29,'Flandes'),
(29,'Fresno'),
(29,'Guamo'),
(29,'Herveo'),
(29,'Honda'),
(29,'Icononzo'),
(29,'Lerida'),
(29,'Libano'),
(29,'Mariquita'),
(29,'Melgar'),
(29,'Murillo'),
(29,'Natagaima'),
(29,'Ortega'),
(29,'Piedras'),
(29,'Planadas'),
(29,'Prado '),
(29,'Purificación'),
(29,'Rioblanco'),
(29,'Roncesvalles'),
(29,'Rovira'),
(29,'Saldana'),
(29,'San Antonio'),
(29,'San Luis'),
(29,'San Isabel'),
(29,'Suarez'),
(29,'Valle de S. Juan'),
(29,'Venadillo'),
(29,'Villahermosa'),
(29,'Villarrica '),
(30,'Cali'),
(30,'Alcala'),
(30,'Andalucia'),
(30,'Ansermanuevo'),
(30,'Argelia'),
(30,'Atlántico'),
(30,'Buenaventura'),
(30,'Buga'),
(30,'Bugalagrande'),
(30,'Caicedonia'),
(30,'Calima (Darien)'),
(30,'Candelaria'),
(30,'Cartago'),
(30,'Dagua'),
(30,'El Aguila'),
(30,'El Cairo'),
(30,'El Cerrito'),
(30,'El Dovio'),
(30,'Florida'),
(30,'Ginebra'),
(30,'Guacari'),
(30,'Jamundi'),
(30,'La Cumbre'),
(30,'La Unión'),
(30,'La Victoria'),
(30,'Obando'),
(30,'Palmira'),
(30,'Pradera'),
(30,'Restrepo'),
(30,'Riofrio'),
(30,'Roldanillo'),
(30,'San Pedro'),
(30,'Sevilla'),
(30,'Toro'),
(30,'Trujillo'),
(30,'Tulua'),
(30,'Ulloa'),
(30,'Versalles'),
(30,'Vijes'),
(30,'Yotoco'),
(30,'Yumbo'),
(30,'Zarzal'),
(31,'Mitú'),
(31,'C.D. Caruru'),
(31,'C.D. Pacoa'),
(31,'C.D. Villa Fátima'),
(31,'C.D. Taraira'),
(31,'C.D. Papunahua'),
(31,'C.D. Acaricuara'),
(31,'C.D. Yavarate'),
(32,'Puerto Carreño'),
(32,'Cumaribo'),
(32,'La Primavera'),
(32,'Santa Rosalía ');

