/*
 * GUIConsInv.java
 *
 * Created on 04/08/2012, 02:51:30 PM
 */
package Vista;

import Modelo.Compra;
import Modelo.Insumo;
import Modelo.Proveedor;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class GUIConsInv extends Interfaz{
    private GUIPrincipal p;

    /** Creates new form GUIConsInv */
    public GUIConsInv(GUIPrincipal principal) {
        initComponents();
        this.p=principal;
        this.p.forms.add(this);
        this.setSize(700, 410);
        setLocationRelativeTo(null);
    }
    
    private void cargarTablaIns(){
        AbstractTableModel datosIns= Insumo.tablaIns();
        this.tablaIns.setModel(datosIns);
        this.tablaIns.setDefaultRenderer(Boolean.class, new MyTableRenderer.ImageRenderer());
    }
    
    private void cargarTablaPro(){
        AbstractTableModel datosPro= Proveedor.tablaProv();
        this.tablaPro.setModel(datosPro);
        this.tablaPro.setDefaultRenderer(Boolean.class, new MyTableRenderer.ImageRenderer());
    }
    
    private void cargarTablaCompra(){        
        DefaultTableModel datosCompra= Compra.tablaCompra();
        this.tablaCom.setModel(datosCompra);
        this.tablaCom.getColumnModel().getColumn(0).setMaxWidth(40);
        this.tablaCom.getColumnModel().getColumn(0).setMinWidth(40);
        this.tablaCom.getColumnModel().getColumn(1).setMaxWidth(400);
        this.tablaCom.getColumnModel().getColumn(1).setMinWidth(400);
        this.tablaCom.setRowHeight(43);// el tama�o de las celulas o celdas
        JTextField textField = new JTextField();
        textField.setBorder(BorderFactory.createEmptyBorder());
        DefaultCellEditor editor = new DefaultCellEditor(textField);
        editor.setClickCountToStart(1);
        //this.tablaCom.getColumn(this.tablaCom.getColumnName(1)).setCellEditor(new MyTableRenderer.ButtonsEditor(tablaCom));
        TableColumn column = tablaCom.getColumnModel().getColumn(2);
		    /***************A�ADADO LAS CLASES EDITAR y VISTA PREVIA**************************/
		    column.setCellRenderer(new MyTableRenderer.ButtonsRenderer());
		    column.setCellEditor(new MyTableRenderer.ButtonsEditor(tablaCom));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIns = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPro = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCom = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBorder(null);
        jPanel1.setLayout(new java.awt.BorderLayout());

        tablaIns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaIns);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Insumos", jPanel1);

        jPanel2.setBorder(null);
        jPanel2.setLayout(new java.awt.BorderLayout());

        tablaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaPro);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Proveedores", jPanel2);

        jPanel3.setBorder(null);
        jPanel3.setLayout(new java.awt.BorderLayout());

        tablaCom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaCom);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Compras", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.cargarTablaIns();
        this.cargarTablaPro();
        this.cargarTablaCompra();
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaCom;
    private javax.swing.JTable tablaIns;
    private javax.swing.JTable tablaPro;
    // End of variables declaration//GEN-END:variables
}
