/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author MICHAEL
 */
public class ModalLote extends javax.swing.JDialog {

    private int cantidadPollos;
    private int clima, tipoGranja;
    /**
     * Creates new form ModalLote
     */
    public ModalLote(java.awt.Frame parent, boolean modal, Object[] datos) {
        super(parent, modal);
        initComponents();
        SpinnerNumberModel spm = (SpinnerNumberModel) spnCantidad.getModel();
        spm.setMaximum(Integer.parseInt(datos[2].toString()));
        cantidadPollos = Integer.parseInt(datos[2].toString());
        GUIGranja g = (GUIGranja) parent;
        clima = g.Clima();
        tipoGranja=g.getTipo();
        jLabel12.setVisible(false);
        cilindros.setVisible(false);
        calculoElementos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCriadoras = new javax.swing.ButtonGroup();
        bgBebederos = new javax.swing.ButtonGroup();
        bgComederos = new javax.swing.ButtonGroup();
        bgVentiladores = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        cmbInicio = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbFinal = new de.wannawork.jcalendar.JCalendarComboBox();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        electrica = new javax.swing.JRadioButton();
        gas = new javax.swing.JRadioButton();
        criadoras = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bandejas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        manual = new javax.swing.JRadioButton();
        automatico = new javax.swing.JRadioButton();
        niple = new javax.swing.JRadioButton();
        bebederos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tubular = new javax.swing.JRadioButton();
        automatic = new javax.swing.JRadioButton();
        comederos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        grande = new javax.swing.JRadioButton();
        pequeño = new javax.swing.JRadioButton();
        ventiladores = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bombillos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        equipo = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        cantidad1 = new javax.swing.JLabel();
        cilindros = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear lote");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Cantidad Inicial:");

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        spnCantidad.setAutoscrolls(true);
        spnCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCantidadStateChanged(evt);
            }
        });

        jLabel1.setText("Fecha Inicio:");

        cmbInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cmbInicioStateChanged(evt);
            }
        });

        jLabel2.setText("Fecha Final:");

        cmbFinal.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cmbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setText("Aceptar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipos Requeridos"));

        jLabel3.setText("CRIADORAS:");

        bgCriadoras.add(electrica);
        electrica.setSelected(true);
        electrica.setText("Electrica");
        electrica.setToolTipText("1 Criadora para 250 Pollos");
        electrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricaActionPerformed(evt);
            }
        });

        bgCriadoras.add(gas);
        gas.setText("Gas");
        gas.setToolTipText("1 Criadora para 500 Pollos");
        gas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasActionPerformed(evt);
            }
        });

        criadoras.setEditable(false);
        criadoras.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("BANDEJAS:");

        bandejas.setEditable(false);
        bandejas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("1 Bandeja para 50 pollos");

        jLabel7.setText("BEBEDEROS:");

        bgBebederos.add(manual);
        manual.setSelected(true);
        manual.setText("Manual");
        manual.setToolTipText("1 Bebedero para 50 Pollos");
        manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualActionPerformed(evt);
            }
        });

        bgBebederos.add(automatico);
        automatico.setText("Automatico");
        automatico.setToolTipText("1 Bebedero para 80 Pollos");
        automatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automaticoActionPerformed(evt);
            }
        });

        bgBebederos.add(niple);
        niple.setText("Niple");
        niple.setToolTipText("1 Bebedero para 12 Pollos");
        niple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nipleActionPerformed(evt);
            }
        });

        bebederos.setEditable(false);
        bebederos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setText("COMEDEROS:");

        bgComederos.add(tubular);
        tubular.setSelected(true);
        tubular.setText("Tubular");
        tubular.setToolTipText("1 Comedero (Frio para 35 Pollos) (Calido para 40 Pollos)");
        tubular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tubularActionPerformed(evt);
            }
        });

        bgComederos.add(automatic);
        automatic.setText("Automatico");
        automatic.setEnabled(false);

        comederos.setEditable(false);
        comederos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        comederos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comederosKeyTyped(evt);
            }
        });

        jLabel9.setText("VENTILADORES:");

        bgVentiladores.add(grande);
        grande.setSelected(true);
        grande.setText("Grande");
        grande.setToolTipText("1 Ventilador para 500 Pollos");
        grande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandeActionPerformed(evt);
            }
        });

        bgVentiladores.add(pequeño);
        pequeño.setText("Pequeño");
        pequeño.setToolTipText("1 Ventilador para 250 Pollos");
        pequeño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pequeñoActionPerformed(evt);
            }
        });

        ventiladores.setEditable(false);
        ventiladores.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ventiladores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ventiladoresKeyTyped(evt);
            }
        });

        jLabel10.setText("BOMBILLOS:");

        bombillos.setEditable(false);
        bombillos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bombillos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bombillosKeyTyped(evt);
            }
        });

        jLabel11.setText("40 W (1 Bombillo para 400 Pollos)");

        equipo.setFont(new java.awt.Font("Tahoma", 1, 11));
        equipo.setText("EQUIPO");

        tipo.setFont(new java.awt.Font("Tahoma", 1, 11));
        tipo.setText("TIPO");

        cantidad1.setFont(new java.awt.Font("Tahoma", 1, 11));
        cantidad1.setText("CANTIDAD");

        cilindros.setEditable(false);
        cilindros.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setText("CILINDROS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(72, 72, 72)
                        .addComponent(tubular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(automatic))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(75, 75, 75)
                        .addComponent(manual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(automatico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(niple))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(equipo)
                        .addGap(160, 160, 160)
                        .addComponent(tipo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(electrica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gas))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(grande)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pequeño)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cilindros))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bombillos)
                    .addComponent(ventiladores)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(criadoras)
                            .addComponent(bandejas)
                            .addComponent(bebederos)
                            .addComponent(comederos, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(cantidad1)
                            .addGap(9, 9, 9))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipo)
                            .addComponent(equipo))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(electrica)
                        .addComponent(gas)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criadoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bandejas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bebederos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manual)
                    .addComponent(automatico)
                    .addComponent(niple)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comederos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tubular)
                    .addComponent(automatic)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ventiladores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grande)
                    .addComponent(pequeño)
                    .addComponent(jLabel9))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10))
                    .addComponent(bombillos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jButton1.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comederosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comederosKeyTyped
        // TODO add your handling code here:
        Interfaz.soloNum(evt);
    }//GEN-LAST:event_comederosKeyTyped

    private void ventiladoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ventiladoresKeyTyped
        // TODO add your handling code here:
        Interfaz.soloNum(evt);
    }//GEN-LAST:event_ventiladoresKeyTyped

    private void bombillosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bombillosKeyTyped
        // TODO add your handling code here:
        Interfaz.soloNum(evt);
    }//GEN-LAST:event_bombillosKeyTyped

    private void electricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricaActionPerformed
        calcularCriadoras(0);
    }//GEN-LAST:event_electricaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void spnCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCantidadStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spnCantidadStateChanged

    private void gasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasActionPerformed
        // TODO add your handling code here:
        calcularCriadoras(1);
    }//GEN-LAST:event_gasActionPerformed

    private void manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualActionPerformed
        // TODO add your handling code here:
        calcularBebederos(0);
    }//GEN-LAST:event_manualActionPerformed

    private void automaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automaticoActionPerformed
        // TODO add your handling code here:
        calcularBebederos(1);
    }//GEN-LAST:event_automaticoActionPerformed

    private void nipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nipleActionPerformed
        // TODO add your handling code here:
        calcularBebederos(2);
    }//GEN-LAST:event_nipleActionPerformed

    private void tubularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tubularActionPerformed
        // TODO add your handling code here:
        //Comederos
        calcularComederos(0);
    }//GEN-LAST:event_tubularActionPerformed

    private void grandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandeActionPerformed
        // TODO add your handling code here:
        calcularVentiladores(0);
    }//GEN-LAST:event_grandeActionPerformed

    private void pequeñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pequeñoActionPerformed
        // TODO add your handling code here:
        calcularVentiladores(1);
    }//GEN-LAST:event_pequeñoActionPerformed

    private void cmbInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cmbInicioStateChanged
        // TODO add your handling code here:
        if(tipoGranja == 1){
           java.util.Calendar calendar = cmbInicio.getCalendar();
           calendar.add(5, java.util.Calendar.WEEK_OF_MONTH);
           cmbFinal.setCalendar(calendar);
        }
    }//GEN-LAST:event_cmbInicioStateChanged
      
    private void calcularCriadoras(int tipo) {
        String criadora;
        switch (tipo) {
            case 0:
                jLabel12.setVisible(false);
                cilindros.setVisible(false);
                criadoras.setText((int) Math.ceil((double)cantidadPollos/(double)250) + "");
                break;
            case 1:
                criadora = (int) Math.ceil((double)cantidadPollos/(double)800) + "";
                jLabel12.setVisible(true);
                cilindros.setVisible(true);
                cilindros.setText(criadora);
                criadoras.setText(criadora);
                break;
        }
    }
    
    private void calcularBebederos(int tipo) {
        int cantidad =  (tipo==0)?50:
                        (tipo==1)?80:
                        100;
        bebederos.setText((int)Math.ceil((double)cantidadPollos/(double)cantidad)+"");
    }
    
    public void calcularComederos(int tipo) {
        int resp = (int) Math.ceil( (clima==1)?((double)cantidadPollos/(double)35):((double)cantidadPollos/(double)40) );
        comederos.setText(resp + "");
    }
    
    public void calcularVentiladores(int tipo) {
        int cantidad = (tipo==0)?500:250;
        ventiladores.setText((int) Math.ceil((double)cantidadPollos/(double)cantidad)+"");
    }
    
    private void calculoElementos(){
        //Bandejas
        bandejas.setText((int) Math.ceil((double)cantidadPollos/(double)50)+"");
        //Bombillos
        bombillos.setText((int) Math.ceil( (double)cantidadPollos/(double)400)+"");
        calcularCriadoras(0);
        calcularBebederos(0);
        calcularComederos(0);
        calcularVentiladores(0);
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton automatic;
    private javax.swing.JRadioButton automatico;
    private javax.swing.JTextField bandejas;
    private javax.swing.JTextField bebederos;
    private javax.swing.ButtonGroup bgBebederos;
    private javax.swing.ButtonGroup bgComederos;
    private javax.swing.ButtonGroup bgCriadoras;
    private javax.swing.ButtonGroup bgVentiladores;
    private javax.swing.JTextField bombillos;
    private javax.swing.JLabel cantidad1;
    private javax.swing.JTextField cilindros;
    private de.wannawork.jcalendar.JCalendarComboBox cmbFinal;
    private de.wannawork.jcalendar.JCalendarComboBox cmbInicio;
    private javax.swing.JTextField comederos;
    private javax.swing.JTextField criadoras;
    private javax.swing.JRadioButton electrica;
    private javax.swing.JLabel equipo;
    private javax.swing.JRadioButton gas;
    private javax.swing.JRadioButton grande;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton manual;
    private javax.swing.JRadioButton niple;
    private javax.swing.JRadioButton pequeño;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JLabel tipo;
    private javax.swing.JRadioButton tubular;
    private javax.swing.JTextField ventiladores;
    // End of variables declaration//GEN-END:variables
}
