INSERT INTO departamento (cod,nombre) VALUES 
(1,'Amazonas'),
(2,'Antioquia'),
(3,'Arauca'),
(4,'Atlántico'),
(5,'Bolívar'),
(6,'Boyacá'),
(7,'Caldas'),
(8,'Caquetá'),
(9,'Casanare'),
(10,'Cauca'),
(11,'Cesar'),
(12,'Córdoba'),
(13,'Cundinamarca'),
(14,'Chocó'),
(15,'Guainía'),
(16,'Guaviare'),
(17,'Huila'),
(18,'La Guajira'),
(19,'Magdalena'),
(20,'Meta'),
(21,'Nariño'),
(22,'Norte de Santander'),
(23,'Putumayo'),
(24,'Quindío'),
(25,'Risaralda'),
(26,'Santander'),
(27,'San Andrés y Providencia'),
(28,'Sucre'),
(29,'Tolima'),
(30,'Valle'),
(31,'Vaupés'),
(32,'Vichada');